title: ABMI Species
version: 3.0
description: Information on species and habitats monitored by the Alberta Biodiversity Monitoring Institute.

url: http://142.244.198.153
#url: http://localhost:4000
#url: http://species.abmi.ca
#url: http://species.abmi.ca/development

#permalink:   /:categories/:title.html
category: news

include: [".htaccess"]
exclude: ["rscripts","README.md","LICENSE.md","_scripts","NOTES.md"]
timezone: America/Edmonton

taxa:
  - title: Mammals
    url: /pages/mammals.html
    label: mammals
  - title: Birds
    url: /pages/birds.html
    label: birds
  - title: Soil mites
    url: /pages/mites.html
    label: mites
  - title: Vascular plants
    url: /pages/vplants.html
    label: vplants
  - title: Bryophytes
    url: /pages/mosses.html
    label: mosses
  - title: Lichens
    url: /pages/lichens.html
    label: lichens

