title:            ABMI Species Website
version: 2.0
description:      Information on individual species monitored by the Alberta Biodiversity Monitoring Institute.
#url:              http://localhost:4000
url: http://species.abmi.ca/development
#url: http://species.abmi.ca
#url: c:/Dropbox/www/species.abmi.ca/_site
#url: https://dl.dropboxusercontent.com/u/18096698/www
#permalink:   /:categories/:title.html
category: news

# Analytics and webmaster tools stuff goes here
google_analytics:

include: [".htaccess"]
exclude: ["rscripts"]
timezone:    America/New_York

taxa:
#  - title: Mammals
#    url: /mammals/index.html
#    label: mammals
  - title: Birds
    url: /birds/index.html
    label: birds
  - title: Mites
    url: /mites/index.html
    label: mites
  - title: Vascular plants
    url: /vascularplants/index.html
    label: vascularplants
  - title: Bryophytes
    url: /bryophytes/index.html
    label: bryophytes
#  - title: Lichens
#    url: /lichens/index.html
#    label: lichens
