title:            ABMI Species Website
version: 2.0
description:      Information on individual species monitored by the Alberta Biodiversity Monitoring Institute.
#url:              http://localhost:4000
#url: http://species.abmi.ca/development
url: http://species.abmi.ca
#url: c:/Dropbox/www/species.abmi.ca/_site
#url: https://dl.dropboxusercontent.com/u/18096698/www
#permalink:   /:categories/:title.html
category: news

# Analytics and webmaster tools stuff goes here
google_analytics:

include: [".htaccess"]
exclude: ["rscripts","README.md","LICENSE.md"]
timezone:    America/Edmonton

taxa:
  - title: Mammals
    url: /pages/mammals.html
    label: mammals
  - title: Birds
    url: /pages/birds.html
    label: birds
  - title: Soil mites
    url: /pages/mites.html
    label: mites
  - title: Vascular plants
    url: /pages/vplants.html
    label: vplants
  - title: Bryophytes
    url: /pages/mosses.html
    label: mosses
  - title: Lichens
    url: /pages/lichens.html
    label: lichens
